---
- name: copy deb packege to temp directory /tmp/
  copy:
   src: "filebeat-oss-7.1.1-amd64.deb"
   dest: /tmp/

- name: install deb package
  apt:
    deb: /tmp/filebeat-oss-7.1.1-amd64.deb
  name: start filebeat
- name: remove deb package
  file:
   path: /tmp/filebeat-oss-7.1.1-amd64.deb
   state: absent

- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
    mode: '0644'
  notify: restart filebeat

